{% set name = "pyngrok" %}
{% set version = "7.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 808068c8ef8f2d3a0c05b3e73c0c656971732efb67e68a1fe1ff6397e6f7b4c5

build:
  noarch: python
  entry_points:
    - ngrok=pyngrok.ngrok:main
    - pyngrok=pyngrok.ngrok:main
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - PyYAML >=5.1

test:
  imports:
    - pyngrok
  commands:
    - pip check
    - ngrok --help
    - pyngrok --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alexdlaird/pyngrok
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper for ngrok
  description: |
    pyngrok is a Python wrapper for ngrok that manages its own binary, making ngrok available
    via a convenient Python API and the command line.
  doc_url: https://pyngrok.readthedocs.io/
  dev_url: https://github.com/alexdlaird/pyngrok

extra:
  recipe-maintainers:
    - alexdlaird
